"""Extract report provenance and key metrics from QuantStats HTML.

QuantStats HTML is generated by many versions and report layouts.  This parser
keeps extraction intentionally defensive: unavailable provenance becomes
``None`` and unknown table values are skipped so they can be surfaced by the
integrity check rather than guessed.
"""

from __future__ import annotations

from html import unescape
import json
import re
from pathlib import Path
from typing import Any

from bs4 import BeautifulSoup


METRIC_LABELS = {
    "Cumulative Return": "cumulative_return",
    "CAGR﹪": "cagr",
    "CAGR%": "cagr",
    "Sharpe": "sharpe",
    "Prob. Sharpe Ratio": "prob_sharpe_ratio",
    "Smart Sharpe": "smart_sharpe",
    "Sortino": "sortino",
    "Smart Sortino": "smart_sortino",
    "Omega": "omega",
    "Max Drawdown": "max_drawdown",
    "Volatility (ann.)": "annual_volatility",
    "Information Ratio": "information_ratio",
    "Calmar": "calmar",
    "Skew": "skew",
    "Kurtosis": "kurtosis",
    "Risk of Ruin": "risk_of_ruin",
    "Daily Value-at-Risk": "daily_value_at_risk",
    "Expected Shortfall (cVaR)": "expected_shortfall",
    "Profit Factor": "profit_factor",
    "Tail Ratio": "tail_ratio",
    "Win Days": "win_days",
    "Win Month": "win_month",
    "Beta": "beta",
    "Alpha": "alpha",
    "Correlation": "correlation",
}


def _clean_metric_name(value: str) -> str:
    """Normalize whitespace and punctuation in HTML metric labels."""
    return re.sub(r"\s+", " ", value).strip().rstrip(":")


def _parse_number(value: str) -> float:
    """Convert a report cell into a float while preserving NaN placeholders."""
    text = unescape(value).strip().replace("%", "").replace("﹪", "").replace(",", "")
    if text in {"nan", "-", ""}:
        return float("nan")
    return float(text)


def _is_percent(metric: str) -> bool:
    """Return whether a metric is commonly rendered as a percentage."""
    return metric in {
        "cumulative_return",
        "cagr",
        "annual_volatility",
        "max_drawdown",
        "daily_value_at_risk",
        "expected_shortfall",
        "win_days",
        "win_month",
        "correlation",
        "alpha",
        "prob_sharpe_ratio",
        "risk_of_ruin",
    }


def parse_report(report_path: str | Path) -> dict[str, Any]:
    """Parse report metadata, strategy metrics and optional EOY returns."""
    path = Path(report_path)
    html = path.read_text(encoding="utf-8", errors="replace")
    soup = BeautifulSoup(html, "html.parser")
    header = " ".join(soup.stripped_strings)

    benchmark = None
    benchmark_match = re.search(r"Benchmark:\s*([^•|]+)", header)
    if benchmark_match:
        benchmark = benchmark_match.group(1).strip()

    periods_per_year = 252
    periods_match = re.search(r"Periods/Year:\s*(\d+)", header)
    if periods_match:
        periods_per_year = int(periods_match.group(1))

    risk_free_rate = 0.0
    risk_free_match = re.search(r"RF:\s*([-\d.]+)%", header)
    if risk_free_match:
        risk_free_rate = float(risk_free_match.group(1)) / 100

    version_match = re.search(r"QuantStats\s*\(?v?\.?\s*([\d.]+)", header)
    generated_match = re.search(r"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?)", header)
    date_range_match = re.search(r"(\d{1,2} \w+,\s*\d{4})\s*-\s*(\d{1,2} \w+,\s*\d{4})", header)

    metrics: dict[str, float] = {}
    benchmark_metrics: dict[str, float] = {}
    strategy_columns: list[str] = []
    target_table = None
    for table in soup.find_all("table"):
        table_text = " ".join(table.stripped_strings)
        if "Metric" not in table_text or "Cumulative Return" not in table_text:
            continue
        target_table = table
        first_row = table.find("tr")
        if first_row:
            cells = [_clean_metric_name(cell.get_text(" ", strip=True)) for cell in first_row.find_all(["th", "td"])]
            strategy_columns = [value for value in cells[1:] if value and value != "Metric"]
        break

    if target_table is not None:
        for row in target_table.find_all("tr"):
            cells = [cell.get_text(" ", strip=True) for cell in row.find_all(["th", "td"])]
            if len(cells) < 2:
                continue
            label = _clean_metric_name(cells[0])
            canonical = METRIC_LABELS.get(label)
            if canonical is None or len(cells) < 3:
                continue
            try:
                value = _parse_number(cells[-1])
            except ValueError:
                continue
            metrics[canonical] = value
            if _is_percent(canonical) and ("%" in cells[-1] or "﹪" in cells[-1]):
                metrics[canonical] = value / 100

            if len(cells) >= 3:
                try:
                    benchmark_value = _parse_number(cells[1])
                except ValueError:
                    benchmark_value = float("nan")
                if not benchmark_value != benchmark_value:
                    benchmark_metrics[canonical] = benchmark_value
                    if _is_percent(canonical) and "%" in cells[1]:
                        benchmark_metrics[canonical] = benchmark_value / 100
    eoy_table = None
    for table in soup.find_all("table"):
        table_text = " ".join(table.stripped_strings)
        if "EOY Returns" in table_text:
            eoy_table = table
            break

    eoy_returns: dict[str, float] = {}
    if eoy_table is not None:
        for row in eoy_table.find_all("tr"):
            cells = [cell.get_text(" ", strip=True) for cell in row.find_all(["th", "td"])]
            if len(cells) >= 3 and re.fullmatch(r"\d{4}", cells[0]):
                try:
                    eoy_returns[cells[0]] = float(cells[2])
                except ValueError:
                    continue

    return {
        "report_path": str(path.resolve()),
        "report_name": path.name,
        "benchmark": benchmark,
        "periods_per_year": periods_per_year,
        "risk_free_rate": risk_free_rate,
        "report_version": version_match.group(1) if version_match else None,
        "generated_at": generated_match.group(1) if generated_match else None,
        "period_start": date_range_match.group(1) if date_range_match else None,
        "period_end": date_range_match.group(2) if date_range_match else None,
        "strategy_columns": strategy_columns,
        "parsed_metrics": metrics,
        "benchmark_metrics": benchmark_metrics,
        "eoy_returns": eoy_returns,
    }
